Hardened config script, fix bug in upgrade-to-35 script, Preparing to release 0.35

diff --git a/trunk/tools/upgrade-to-035 b/trunk/tools/upgrade-to-035
--- a/trunk/tools/upgrade-to-035
+++ b/trunk/tools/upgrade-to-035
@@ -89,21 +89,39 @@ if [ $DST_SLICE = 0 ]; then
 fi
 
 # Blow away old system.
-dd if=/dev/zero of=/dev/${NANO_DRIVE}s${DST_SLICE} bs=1m count=1 > /dev/null 2>&1
+if ! dd if=/dev/zero of=/dev/${NANO_DRIVE}s${DST_SLICE} bs=1m count=1 > /dev/null 2>&1; then
+	echo "ERROR: Can't initialize destination partition"
+	exit 1
+fi
 
 # This message disturb the ask for password from SSH
 #echo "Upgrading... Please wait."
 
 # Copy in new system
-dd of=/dev/${NANO_DRIVE}s${DST_SLICE} obs=64k
+if ! dd of=/dev/${NANO_DRIVE}s${DST_SLICE} obs=64k; then
+	echo "ERROR: Can't install the upgrade on slice ${DST_SLICE}"
+	exit 1
+fi
 
 # Check that it worked
-fsck_ffs -n /dev/${NANO_DRIVE}s${DST_SLICE}a
+if ! fsck_ffs -n /dev/${NANO_DRIVE}s${DST_SLICE}a; then
+	echo "ERROR: New file system check failed"
+	exit 1
+fi
 
 # Set Label into the new slice
-tunefs -L ${NANO_GLABEL_SYS}s${DST_SLICE}a /dev/${NANO_DRIVE}s${DST_SLICE}a
-tunefs -L ${NANO_GLABEL_SYS}s3 /dev/${NANO_DRIVE}s3
-tunefs -L ${NANO_GLABEL_SYS}s4 /dev/${NANO_DRIVE}s4
+if ! tunefs -L ${NANO_GLABEL_SYS}s${DST_SLICE}a /dev/${NANO_DRIVE}s${DST_SLICE}a; then
+	echo "ERROR: Can't put label on the new filesystem"
+	exit 1
+fi
+if ! tunefs -L ${NANO_GLABEL_SYS}s3 /dev/${NANO_DRIVE}s3; then
+	echo "ERROR: Can't replace old label on cfg slice"
+	exit 1
+fi
+if ! tunefs -L ${NANO_GLABEL_SYS}s4 /dev/${NANO_DRIVE}s4; then
+	echo "ERROR: Can't replace old label on data slice"
+	exit 1
+fi
 
 # Need to compare some files between the old and new partition
 if [ ! -d /tmp/upgrade ]; then
@@ -120,17 +138,37 @@ for f in /tmp/upgrade/etc/fstab /tmp/upgrade/conf/base/etc/fstab /etc/fstab
     done
 #	Compare the loader.conf, and include the diff into the new partition
 #	This file is modify with "system virtualized"
-diff -ruN /boot/loader.conf /tmp/upgrade/boot/loader.conf > /tmp/loader.conf.patch
-patch -s /tmp/upgrade/boot/loader.conf /tmp/loader.conf.patch
+if diff -ruN /boot/loader.conf /tmp/upgrade/boot/loader.conf > /tmp/loader.conf.patch; then
+	if ! patch -s /tmp/upgrade/boot/loader.conf /tmp/loader.conf.patch; then
+		echo "WARNING: Can't patch upgraded /boot/loader.conf"
+		echo "YOU NEED to manually merge your /boot/loader.conf"
+	fi
+fi
 
-umount /tmp/upgrade
-rm -r /tmp/upgrade
+if ! umount /tmp/upgrade; then
+	echo "ERROR: Can't umount new image"
+	exit 1
+fi
+
+if ! rm -r /tmp/upgrade; then
+	echo "WARNING: Can't remove tempdir"
+fi
 
 # Save the config file that include the fstab
 # Don't know if it's usefull
-mount /cfg
-cp /etc/fstab /cfg
-umount /cfg
+if ! mount /cfg; then
+	echo "ERROR: Can't mount /cfg"
+	exit 1
+fi
+if ! cp /etc/fstab /cfg; then
+	echo "ERROR: Can't save fstab"
+	umount /cfg
+	exit 1
+fi
+if ! umount /cfg; then
+	echo "ERROR: Can't umount /cfg"
+	exit 1
+fi
 
 case "${ARCH}" in
         i386|amd64)
