Enable BGP Monitor Protocol on bird… So update the port tree to latest version… which brings python 3.11 as new default python… which brings more than 100M of libraries… which is too big for the existing 900M OS partition… So need to increase the default minimum disk size to 4G :-(

diff --git a/build b/build
--- a/build
+++ b/build
@@ -86,22 +86,31 @@ fi
 # XXX Regression: latest modifications time of dependencies are ignored
 if poudriere -e poudriere.etc ports -ln | grep -q BSDRPp; then
 	echo "Updating poudriere port tree (build_ports.log)..."
-	poudriere -e poudriere.etc ports -u -p BSDRPp -m null -M /usr/local/BSDRP/BSDRP/FreeBSD/ports > build_ports.log
+	if ! poudriere -e poudriere.etc ports -u -p BSDRPp -m null -M /usr/local/BSDRP/BSDRP/FreeBSD/ports > build_ports.log; then
+	echo "failed"
+		tail build_ports.log
+	fi
 else
 	echo "Creating poudriere port tree (build_ports.log).."
-	poudriere -e poudriere.etc ports -c -p BSDRPp -m null -M /usr/local/BSDRP/BSDRP/FreeBSD/ports > build_ports.log
+	if ! poudriere -e poudriere.etc ports -c -p BSDRPp -m null -M /usr/local/BSDRP/BSDRP/FreeBSD/ports > build_ports.log; then
+		echo "failed"
+		tail build_ports.log
+	fi
 fi
 
 # Build the packages
 echo "Building packages (build_ports.log)..."
-poudriere -e poudriere.etc bulk -j BSDRPj -p BSDRPp -f poudriere.etc/poudriere.d/BSDRP-pkglist >> build_ports.log
+if ! poudriere -e poudriere.etc bulk -j BSDRPj -p BSDRPp -f poudriere.etc/poudriere.d/BSDRP-pkglist >> build_ports.log; then
+	echo "failed"
+	tail build_ports.log
+fi
 # Build the firmware image
 # size in bytes
 
 # Notice that we are using a custom pkg.conf files preventing to install useless files
 
 echo "Generating disk image (build_image.log)..."
-poudriere -e poudriere.etc image -t firmware -s 2g \
+poudriere -e poudriere.etc image -t firmware -s 4g \
 	-j BSDRPj -p BSDRPp -n BSDRP -h router.bsdrp.net \
 	-c BSDRP/Files/ \
 	-f poudriere.etc/poudriere.d/BSDRP-pkglist \
