Add 'system rollback' feature, fix typo in package list, update TODO list

diff --git a/trunk/Files/usr/local/sbin/system b/trunk/Files/usr/local/sbin/system
--- a/trunk/Files/usr/local/sbin/system
+++ b/trunk/Files/usr/local/sbin/system
@@ -3,7 +3,7 @@
 # System tool for BSD Router Project 
 # http://bsdrp.net
 #
-# Copyright (c) 2009-2010, The BSDRP Development Team 
+# Copyright (c) 2009-2012, The BSDRP Development Team 
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -44,27 +44,28 @@ usage () {
 		echo "- [quiet] : Display only the warning"
 		exit 0
 		;;
-	virtualized)
-		echo "Optimize the system for running as a VM"
-		exit 0
-		;;
 	integrity)
 		echo "Check system integrity using a reference mtree file"
 		echo "The given file can be .mtree, .mtree.bz2 or .mtree.xz"
 		echo "Note: Do not keep the reference mtree file on the router!"
 		exit 0
 		;;
+	virtualized)
+		echo "Optimize the system for running as a VM"
+		exit 0
+		;;
 	esac
 	# value $0 is the name of the called script
 	echo "Usage: $0 option"
-    echo "  - reboot/reload       : Restart the system"
+	echo "  - check-vm            : Try to detect if used in a VM"
 	echo "  - integrity filename  : Check system integrity using the given reference file"
 	echo "  - halt/stop           : Poweroff the system"
-	echo "  - virtualized         : Optimize for a VM use"
-	echo "  - check-vm            : Try to detect if used in a VM"
-	echo "  - tune            : Tune for routing (not persistent)"
 	echo "  - help/h [option]     : Display this help message. "
-	echo "		if [option] given, display more detail about the option"
+	echo "    if [option] given, display more detail about the option"
+    echo "  - reboot/reload       : Restart the system"
+	echo "  - rollback            : Revert to previous version"
+	echo "  - tune                : Tune for routing (not persistent)"
+	echo "  - virtualized         : Optimize for a VM use"
 	exit 0
 }
 
@@ -108,6 +109,124 @@ ask_save () {
 	fi
 }
 
+#Revert to the other system partition
+#Big part of this function came from the upgrade script
+#TODO: Need to merge the upgrade script and this script
+# 0. Ask a user confirmation
+# 1. Check if there is a previous release
+# 2. Mount the previous and update the fstab
+# 3. Change the active slice and bootloader default choice	
+rollback () {
+	echo -n "Warning: Are you sure to revert to the previous release ? (y/n)"
+	while [ "$USER_CONFIRM" != "y" -a "$USER_CONFIRM" != "n" ]; do
+       	read USER_CONFIRM <&1
+	done
+	if [ "$USER_CONFIRM" = "n" ]; then
+		return 0	
+	fi
+
+	# Get the NANO_GLABEL_SYS variable
+	NANO_GLABEL_SYS=`cut -d '/' -f 2 /etc/nanobsd.conf`
+	# Get the NANO_GLABEL_SYS_FULL variable
+	# (kept the last number: 1 or 2)
+	NANO_GLABEL_SYS_FULL=`mount | grep " / " | cut -d'/' -f4 | cut -d' ' -f1`
+
+	# Get the disk name using its label
+	NANO_DRIVE=`glabel status | grep ufs/${NANO_GLABEL_SYS_FULL} | awk '{print $3}' | cut -d's' -f1`
+
+	# Get the full disk name
+	NANO_FULLDRIVE=`glabel status | grep ufs/${NANO_GLABEL_SYS_FULL} | awk '{print $3}'`
+
+	# Check and set final variable
+	DST_SLICE=0
+
+	if [ `echo $NANO_FULLDRIVE | /usr/bin/grep "s1"` ]; then 
+    	DST_SLICE=1
+    	SRC_SLICE=2
+	fi
+	if [ `echo $NANO_FULLDRIVE | /usr/bin/grep "s2"` ]; then                
+    	DST_SLICE=2
+    	SRC_SLICE=1
+	fi
+
+	if [ $DST_SLICE = 0 ]; then
+    	echo "Can't detect active slice"
+    	exit 1
+	fi
+	
+	# Check if old system was good
+	if ! fsck_ffs -n /dev/${NANO_DRIVE}s${DST_SLICE}a; then
+    	echo "ERROR: Missing or fsck problem on the previous system slice"
+    	exit 1
+	fi
+
+	# Need to compare some files between the old and new partition
+	if [ ! -d /tmp/sysupgrade ]; then
+    	mkdir /tmp/sysupgrade
+	fi
+
+	# Mount the old system slice
+	if ! mount /dev/ufs/${NANO_GLABEL_SYS}s${DST_SLICE}a /tmp/sysupgrade; then
+    	echo "ERROR: Can't mount old system slice"
+    	exit 1
+	fi
+	#   Adapt fstab of the old system
+	for f in /tmp/sysupgrade/etc/fstab /tmp/sysupgrade/conf/base/etc/fstab /etc/fstab; do
+        sed -i "" "s/${NANO_GLABEL_SYS}s${SRC_SLICE}a/${NANO_GLABEL_SYS}s${DST_SLICE}a/g" $f
+    	done	
+
+	if ! umount /tmp/sysupgrade; then
+    	echo "ERROR: Can't umount old system slice"
+    	exit 1
+	fi
+
+	if ! rm -r /tmp/sysupgrade; then
+    	echo "WARNING: Can't remove tempdir"
+	fi
+
+	# Save the config file that include the fstab
+	# Don't know if it's usefull
+	if ! mount /cfg; then
+    	echo "ERROR: Cant't mount /cfg"
+    	exit 1
+	fi
+	if ! cp /etc/fstab /cfg; then
+    	echo "ERROR: Can't save fstab"
+    	umount /cfg
+    	exit 1
+	fi
+	if ! umount /cfg; then
+    	echo "ERROR: Can't umount /cfg"
+    	exit 1
+	fi
+	case "${ARCH}" in
+        i386|amd64)
+                if ! boot0cfg -s ${DST_SLICE} -t 18 -v ${NANO_DRIVE}; then
+                    echo "ERROR: Can't update FreeBSD bootloader"
+                    exit 1
+                fi
+                if ! gpart set -a active -i ${DST_SLICE} ${NANO_DRIVE}; then
+                    echo "ERROR: Can't update active partition"
+                    exit 1
+                fi
+                ;;
+        arm)
+                echo "arm upgrade script not tested!"   
+                if ! gpart set -a active -i ${DST_SLICE} ${NANO_DRIVE}; then
+                    echo "ERROR: Can't update active partition"
+                    exit 1
+                fi
+                ;;
+        sparc64)
+                echo "You need to configure OBP for booting on"
+                ;;
+	esac
+
+# Log
+echo "BSDRP system rollback complete"
+logger BSDRP system rollback complete
+
+}
 # Tune system
 tune () {
 	echo "Tune system for routing"
@@ -320,26 +439,29 @@ else
 fi
 
 case "$FIRST_OPTION" in
+    integrity)
+        integrity
+        ;;
+    check-vm)
+        check_vm
+        ;;
 	halt|stop)
 		sys_halt
 		;;
+    help|h)
+        usage
+        ;;
 	reboot|reload)
 		sys_reboot
 		;;
+	rollback)
+		rollback
+		;;
+    tune)
+        tune
+        ;;
 	virtualized)
 		sys_virtualized
-		;;
-	check-vm)
-        check_vm
-        ;;
-	integrity)
-		integrity
-		;;
-	tune)
-		tune
-		;;
-	help|h)
-		usage
 		;;
 	*)
 		usage
