graphpath, start to add Linux support

diff --git a/BSDRP/Files/usr/local/bin/graphpath b/BSDRP/Files/usr/local/bin/graphpath
--- a/BSDRP/Files/usr/local/bin/graphpath
+++ b/BSDRP/Files/usr/local/bin/graphpath
@@ -187,19 +187,141 @@ draw_me () {
 	printf '| MAC:  %-18s   |\n' ${src_interface_mac}
 	printf '| IP:   %-18s   |\n' ${src_interface_ip}
 	printf '| net:  %-18s   |\n' ${src_destination}
-	printf '| mask: %-18s   |\n' ${src_mask}
+	[ -n "${src_mask}" ] && printf '| mask: %-18s   |\n' ${src_mask}
 	echo "|                            |"
 	echo "|         THIS ${device}        |"
 	if [ "${src_interface}" != "${dst_interface}" ]; then
 		# First model type, need to draw lower part
 		echo "|                            |"
     	printf '| net:  %-18s   |\n' ${dst_destination}
-    	printf '| mask: %-18s   |\n' ${dst_mask}
+    	[ -n "${dst_mask}" ] && printf '| mask: %-18s   |\n' ${dst_mask}
     	printf '| IP:   %-18s   |\n' ${dst_interface_ip}
     	printf '| MAC:  %-18s   |\n' ${dst_interface_mac}
     	printf '| IF:   %-18s   |\n' ${dst_interface}
 	fi
 	echo "+----------------------------+"
+}
+
+get_freebsd() {
+	# Extract routes data
+	# Check if router enabled
+	[ $(sysctl -n net.inet.ip.forwarding) -eq 0 ] && forwarding=false || forwarding=true
+	[ $(sysctl -n net.inet6.ip6.forwarding) -eq  0 ] && forwarding6=false || forwarding6=true
+
+	# Populate src_* and dst_* variables
+	for i in src dst; do
+		eval "
+			# if route didn't fill _gateway, this mean its directly connected
+			${i}_gateway="direct"
+
+			# some route crossing PPP tun doesn't have _mask
+			${i}_mask="255.255.255.255"
+
+			# call route only once
+			route -n get \${${i}_ip} > /tmp/output.txt || die \"Route towards \${${i}_ip} not found\"
+
+			# Output are like this one:
+			#   route to: 2.2.2.2
+			#destination: 0.0.0.0
+			#       mask: 0.0.0.0
+			#    gateway: 192.168.1.100
+			#        fib: 0
+			#  interface: bxe3
+			#      flags: <UP,GATEWAY,DONE,STATIC>
+			# recvpipe  sendpipe  ssthresh  rtt,msec    mtu        weight    expire
+			#       0         0         0         0      1500         1         0
+
+			while read line; do
+				data=\$(echo \$line | cut -d ':' -f 1)
+				case \$data in
+				\"route to\")
+					${i}_routeto=\$(echo \$line | cut -d ':' -f 2 | tr -d ' ')
+					;;
+				destination)
+					${i}_destination=\$(echo \$line | cut -d ':' -f 2 | tr -d ' ')
+					;;
+				mask)
+					${i}_mask=\$(echo \$line | cut -d ':' -f 2 | tr -d ' ')
+					;;
+				gateway)
+					${i}_gateway=\$(echo \$line | cut -d ':' -f 2 | tr -d ' ')
+					${i}_gateway_arp=\$(arp -n \${${i}_gateway} | cut -d ' ' -f 4)
+					;;
+				fib)
+					${i}_fib=\$(echo \$line | cut -d ':' -f 2)
+						;;
+				interface)
+					${i}_interface=\$(echo \$line | cut -d ':' -f 2 | tr -d ' ')
+					${i}_interface_mac=\$(ifconfig \${${i}_interface} link | grep ether | cut -d ' ' -f 2)
+					${i}_interface_ip=\$(ifconfig \${${i}_interface} inet | grep inet | cut -d ' ' -f 2)
+					;;
+				flags)
+					${i}_flags=\$(echo \$line | cut -d ':' -f 2)
+					;;
+				esac
+			done < /tmp/output.txt
+			if [ \"\${${i}_gateway}\" == \"direct\" ]; then
+				${i}_gateway_arp=\$(arp -n \${${i}_ip} | cut -d ' ' -f 4)
+				[ \"\${${i}_gateway_arp}\" == \"no\" ] && ${i}_gateway_arp='empty' || true
+			fi
+		"
+	done
+}
+
+get_linux () {
+	# Extract routes data
+	# Check if router enabled
+	[ $(cat /proc/sys/net/ipv4/ip_forward) -eq 0 ] && forwarding=false || forwarding=true
+	[ $(cat /proc/sys/net/ipv6/conf/all/forwarding) -eq  0 ] && forwarding6=false || forwarding6=true
+
+	# Populate src_* and dst_* variables
+	for i in src dst; do
+		eval "
+			# if route didn't fill _gateway, this mean its directly connected
+			${i}_gateway="direct"
+
+			# No mask on linux (using a / into the destination variable)
+			${i}_mask=""
+
+			# call route only once
+			ip -o route get \${${i}_ip} > /tmp/output.txt
+			# Output are like this one:
+			# non consistent output... STUPID Linux!!!!!
+			# 2.2.2.3 via 10.253.52.126 dev eth2 src 10.253.52.115 \ cache
+			# 192.168.237.116 dev eth1.337 src 192.168.237.115 \    cache
+			# 10.253.52.124 dev eth2 src 10.253.52.115 \    cache
+
+			# local 127.0.0.1 dev lo src 127.0.0.1
+
+			read ip via gateway dev if src if_ip < /tmp/output.txt
+			if [ \"\${via}\" == \"via\" ]; then
+				${i}_routeto=\${${i}_ip}
+				${i}_gateway=\${gateway}
+				${i}_gateway_arp=\$(ip neigh show \${${i}_gateway} | cut -d ' ' -f 5)
+				${i}_interface=\${if}
+				${i}_interface_ip=\$(echo \${if_ip} | cut -d ' ' -f1)
+			elif [ \"\${via}\" == \"dev\" ]; then
+				${i}_routeto=\${${i}_ip}
+				${i}_interface=\${gateway}
+				${i}_interface_ip=\$(echo \${if} | cut -d ' ' -f1)
+			else
+				${i}_interface=\${dev}
+			fi
+			${i}_interface_mac=\$(ip link show \${${i}_interface}| grep ether | tr -s ' ' | cut -d ' ' -f 3)
+
+			# We still need other data (destination subnet and mask)
+			# need to use another ip commande for getting the subnet matching
+			# ip route show to match 192.168.229.58
+			# default via 10.253.52.126 dev eth2 onlink
+			# 192.168.229.56/29 via 192.168.237.100 dev eth1.337
+			${i}_destination=\$(ip -o route show to match \${${i}_ip} | grep \${if} | cut -d ' ' -f1)
+
+			if [ \"\${${i}_gateway}\" == \"direct\" ]; then
+				${i}_gateway_arp=\$(ip neigh show \${${i}_routeto} | cut -d ' ' -f 5)
+				[ \"\${${i}_gateway_arp}\" == \"no\" ] && ${i}_gateway_arp='empty' || true
+			fi
+		"
+	done
 }
 
 ### Main function ###
@@ -208,80 +330,32 @@ draw_me () {
 
 src_ip=$1
 dst_ip=$2
+device="ROUTER"
 
 # Small checks
 [ "${src_ip}" == "${dst_ip}" ] && die "Same source and destination IP addresses"
 
-# Check if router enabled
-[ $(sysctl -n net.inet.ip.forwarding) -eq 0 ] && forwarding=false || forwarding=true
-[ $(sysctl -n net.inet6.ip6.forwarding) -eq  0 ] && forwarding6=false || forwarding6=true
+OS=$(uname)
+case ${OS} in
+	FreeBSD)
+		get_freebsd
+		;;
+	Linux)
+		get_linux
+		;;
+	*)
+		die "This script was not tested on $(OS)"
+		;;
+esac
 
-device="ROUTER"
 if [ $forwarding = false -o $forwarding6 = false ]; then
 	device="HOST  "
-	echo "This tool is mainly designed for drawing router or firewall routing view"
 fi
 
 
-# Populate src_* and dst_* variables
+[ "${device}" == "HOST" ] && echo "This tool is mainly designed for drawing router or firewall routing view"
 
-for i in src dst; do
-	eval "
-		# if route didn't fill _gateway, this mean its directly connected
-		${i}_gateway="direct"
-
-		# some route crossing PPP tun doesn't have _mask
-		${i}_mask="255.255.255.255"
-
-		# call route only once
-		route -n get \${${i}_ip} > /tmp/output.txt || die \"Route towards \${${i}_ip} not found\"
-
-		# Output are like this one:
-		#   route to: 2.2.2.2
-		#destination: 0.0.0.0
-		#       mask: 0.0.0.0
-		#    gateway: 192.168.1.100
-		#        fib: 0
-		#  interface: bxe3
-		#      flags: <UP,GATEWAY,DONE,STATIC>
-		# recvpipe  sendpipe  ssthresh  rtt,msec    mtu        weight    expire
-		#       0         0         0         0      1500         1         0
-
-		while read line; do
-			data=\$(echo \$line | cut -d ':' -f 1)
-			case \$data in
-			\"route to\")
-				${i}_routeto=\$(echo \$line | cut -d ':' -f 2 | tr -d ' ')
-				;;
-			destination)
-				${i}_destination=\$(echo \$line | cut -d ':' -f 2 | tr -d ' ')
-				;;
-			mask)
-				${i}_mask=\$(echo \$line | cut -d ':' -f 2 | tr -d ' ')
-				;;
-			gateway)
-				${i}_gateway=\$(echo \$line | cut -d ':' -f 2 | tr -d ' ')
-				${i}_gateway_arp=\$(arp -n \${${i}_gateway} | cut -d ' ' -f 4)
-				;;
-			fib)
-				${i}_fib=\$(echo \$line | cut -d ':' -f 2)
-				;;
-			interface)
-				${i}_interface=\$(echo \$line | cut -d ':' -f 2 | tr -d ' ')
-				${i}_interface_mac=\$(ifconfig \${${i}_interface} link | grep ether | cut -d ' ' -f 2)
-				${i}_interface_ip=\$(ifconfig \${${i}_interface} inet | grep inet | cut -d ' ' -f 2)
-				;;
-			flags)
-				${i}_flags=\$(echo \$line | cut -d ':' -f 2)
-				;;
-			esac
-		done < /tmp/output.txt
-		if [ \"\${${i}_gateway}\" == \"direct\" ]; then
-			${i}_gateway_arp=\$(arp -n \${${i}_ip} | cut -d ' ' -f 4)
-			[ \"\${${i}_gateway_arp}\" == \"no\" ] && ${i}_gateway_arp='empty' || true
-		fi
-	"
-done
+### Start ASCII drawing
 
 if [ "${src_interface}" != "${dst_interface}" ]; then
 	# First model family
@@ -300,7 +374,7 @@ else
 	if [ "${src_gateway}" == "${dst_gateway}" ]; then
 		echo "            --+---+-----------------------------+---"
 		echo "              | "
-		draw_block src 'ROUTER' ${src_gateway} direct ${src_gateway_arp}
+		draw_block src 'ROUTER' ${src_gateway} direct ${src_gateway_arp} ""
 	else
 		if [ "${src_gateway}" != "direct" -a "${dst_gateway}" == "direct" ]; then
 			draw_block src 'ROUTER TOWARDS SOURCE' ${src_gateway} direct ${src_gateway_arp} "right"
