Add mrtparse, fix exabgp rc script, update netmap pkt-gen

diff --git a/BSDRP/patches/ports.exabgp.patch b/BSDRP/patches/ports.exabgp.patch
--- a/BSDRP/patches/ports.exabgp.patch
+++ b/BSDRP/patches/ports.exabgp.patch
@@ -1,6 +1,6 @@
 Index: net/exabgp/Makefile
 ===================================================================
---- net/exabgp/Makefile	(revision 508493)
+--- net/exabgp/Makefile	(revision 518433)
 +++ net/exabgp/Makefile	(working copy)
 @@ -2,45 +2,53 @@
  # $FreeBSD$
@@ -38,8 +38,8 @@ Index: net/exabgp/Makefile
  NO_ARCH=	yes
  
 +SHEBANG_FILES=	etc/exabgp/run/*.run \
-+				etc/exabgp/run/*.pl \
-+				etc/exabgp/run/*.py
++		etc/exabgp/run/*.pl \
++		etc/exabgp/run/*.py
 +
 +USE_GITHUB=	yes
 +GH_ACCOUNT=	Exa-Networks
@@ -75,7 +75,7 @@ Index: net/exabgp/Makefile
  do-install-EXAMPLES-on:
 Index: net/exabgp/distinfo
 ===================================================================
---- net/exabgp/distinfo	(revision 508493)
+--- net/exabgp/distinfo	(revision 518433)
 +++ net/exabgp/distinfo	(working copy)
 @@ -1,3 +1,3 @@
 -TIMESTAMP = 1531317755
@@ -84,6 +84,45 @@ Index: net/exabgp/distinfo
 +TIMESTAMP = 1565637826
 +SHA256 (Exa-Networks-exabgp-4.1.2_GH0.tar.gz) = 5921e002f196e814d02349a15c250b1fc8bf45c7299b6b652d2fed04eebb529a
 +SIZE (Exa-Networks-exabgp-4.1.2_GH0.tar.gz) = 2912897
+Index: net/exabgp/files/exabgp.in
+===================================================================
+--- net/exabgp/files/exabgp.in	(revision 518433)
++++ net/exabgp/files/exabgp.in	(working copy)
+@@ -25,7 +25,7 @@
+ required_files=${exabgp_conf}
+ 
+ command="%%PYTHON_CMD%%"
+-command_args="-m exabgp --folder /usr/local/etc/exabgp ${exabgp_conf}"
++command_args="-m exabgp ${exabgp_conf}"
+ 
+ configtest_cmd="exabgp_configtest"
+ start_precmd="exabgp_precmd"
+@@ -45,7 +45,7 @@
+ exabgp_configtest()
+ {
+ 	echo "Performing sanity check on ${name} configuration."
+-	result=$(env exabgp.log.configuration=true exabgp.daemon.daemonize=false exabgp.log.level=ERR exabgp.log.destination=stdout ${command} -m ${name} --folder /usr/local/etc/exabgp -t ${exabgp_conf} 2>&1)
++	result=$(env exabgp.log.configuration=true exabgp.daemon.daemonize=false exabgp.log.level=ERR exabgp.log.destination=stdout ${command} -m ${name} /usr/local/etc/exabgp -t ${exabgp_conf} 2>&1)
+ 	if [ ! -z "${result}" ]; then
+ 		echo "${result}"
+ 		err 1 "Failed to validate configuration file, aborting."
+@@ -54,9 +54,14 @@
+ 
+ exabgp_precmd()
+ {
++	if ! [ -d /var/run/${name} ]; then
++		install -d -o _bgpd -g _bgpd -m 755 /var/run/${name}
++		install -d -o _bgpd -g _bgpd -m 755 /var/log/${name}
++		mkfifo -m 600 /var/run/exabgp/exabgp.in
++		mkfifo -m 600 /var/run/exabgp/exabgp.out
++		chown _bgpd:_bgpd /var/run/exabgp/exabgp.*
++	fi
+ 	exabgp_configtest
+-	install -d -o _bgpd -g _bgpd -m 755 /var/run/${name}
+-	install -d -o _bgpd -g _bgpd -m 755 /var/log/${name}
+ 	rm -f ${pidfile}
+ }
+ 
 Index: net/exabgp/files/patch-setup.py
 ===================================================================
 --- net/exabgp/files/patch-setup.py	(nonexistent)
@@ -116,7 +155,7 @@ Added: svn:mime-type
 \ No newline at end of property
 Index: net/exabgp/pkg-plist
 ===================================================================
---- net/exabgp/pkg-plist	(revision 508493)
+--- net/exabgp/pkg-plist	(revision 518433)
 +++ net/exabgp/pkg-plist	(working copy)
 @@ -1,391 +1,97 @@
  @sample etc/exabgp/exabgp.env.sample
