Migrate the x86 nanobsd function to use gpart in place of fdisk, enable SUJ after an expand-slice

diff --git a/Files/usr/local/sbin/system b/Files/usr/local/sbin/system
--- a/Files/usr/local/sbin/system
+++ b/Files/usr/local/sbin/system
@@ -153,6 +153,10 @@ expand_data_slice () {
 		exit 1
 	fi
 
+	if ! tunefs -j ${boot_dev}s4; then
+		echo "WARNING: Can't enable soft updates journaling"
+	fi
+
 	echo "Done"
 
 }
