Improve and simplify system tools

diff --git a/trunk/Files/usr/local/bin/system b/trunk/Files/usr/local/bin/system
--- a/trunk/Files/usr/local/bin/system
+++ b/trunk/Files/usr/local/bin/system
@@ -121,15 +121,16 @@ sys_halt () {
 
 # Check if system is under a VM
 check_vm () {
-	VM_FOUND=0
-    if ! `sysctl dev.acpi.0.%desc | grep -q QEMU`; then
-        VM_FOUND=1
+    if [ `sysctl dev.acpi.0.%desc | grep -q QEMU` ]; then
+        VM_FOUND=0
+	else
+		VM_FOUND=1
     fi
     # Need to add vmware, virtualbox, etc...
     if [ $VM_FOUND ]; then
         echo "VM usage detected"
     fi
-    if `grep -q "kern.hz=50" /boot/loader.conf`; then
+    if [ `grep -q "kern.hz=50" /boot/loader.conf` ]; then
         NOT_TUNED=0
     else
         NOT_TUNED=1
@@ -140,6 +141,7 @@ check_vm () {
     fi
     exit 0
 }
+
 # Create a new image with acceptable performance under virtualization (quemu, vmware, virtualbox, etc...)
 sys_virtualized () {
 	echo "This step will configure BSDRP for being use as a VM"
@@ -154,42 +156,19 @@ sys_virtualized () {
 		echo "Canceling"
 		exit 0
 	fi
-	# The next part is a copy/past of upgrade function... need to create shared function .subr for avoiding copy/past
-	#Get the active system slice number and use the upgrade script
-	NANO_GLABEL_SYS_FULL=`mount | grep " / " | cut -d'/' -f4 | cut -d' ' -f1`
-
-	# Get the disk name using its label
-	NANO_DRIVE=`glabel status | grep ufs/${NANO_GLABEL_SYS_FULL} | awk '{print $3}' | cut -d's' -f1`
-
-	# Get the full disk name
-	NANO_FULLDRIVE=`glabel status | grep ufs/${NANO_GLABEL_SYS_FULL} | awk '{print $3}'`
-
-	# Check and set final variable
-	DST_SLICE=0
-
-	if [ `echo $NANO_FULLDRIVE | /usr/bin/grep "s1"` ]; then
-        DST_SLICE=2
-        SRC_SLICE=1
-	fi
-	if [ `echo $NANO_FULLDRIVE | /usr/bin/grep "s2"` ]; then
-    	DST_SLICE=1
-        SRC_SLICE=2
-	fi
-	if [ $DST_SLICE = 0 ]; then
-        echo "Can't detect active slice"
-        exit 1
-	fi
-	
-	# Use upgrade for copying active partition over passive partition
-	dd if=/dev/${NANO_DRIVE}s${SRC_SLICE} | upgrade
+	# Get the drive mounted	
+	NANO_DRIVE=`mount | grep " / " | cut -d' ' -f1`
 	
 	# Now we need to mount this filesystem and add the modification:
-	if [ `mkdir /tmp/freetibet` ]; then
+	if [ -d /tmp/freetibet ]; then
+		echo "/tmp/freetibet allready exist ?"
+		exit 1
+	elif [ `mkdir /tmp/freetibet` ]; then
 		echo "Can't creat tempory directory"
 		exit 1
     fi
-	if [ `mount /dev/ufs/BSDRP${DST_SLICE} /tmp/freetibet` ]; then
-        echo "Can't mount /dev/ufs/BSDRP${DST_SLICE}"
+	if [ `mount ${NANO_DRIVE} /tmp/freetibet` ]; then
+        echo "Can't mount ${NANO_DRIVE}"
         exit 1
     fi
 	
@@ -204,7 +183,7 @@ sys_virtualized () {
         exit 1
     fi
 
-exit 0
+	exit 0
 
 
 }
