Add 'config diff factory' for comparing changes with default configuration

diff --git a/trunk/BSDRP/Files/usr/local/sbin/config b/trunk/BSDRP/Files/usr/local/sbin/config
--- a/trunk/BSDRP/Files/usr/local/sbin/config
+++ b/trunk/BSDRP/Files/usr/local/sbin/config
@@ -49,7 +49,8 @@ usage () {
 		;;
 	diff)
 		echo "Option for diff:"
-		echo " - fast : Return 1 if changes found, 0 otherwise"
+		echo " - quiet : Return 1 if changes found, 0 otherwise"
+		echo " - factory : compare against default configuration"
 		exit 0
 		;;
 	put)
@@ -70,7 +71,7 @@ usage () {
 
 # value $0 is the name of the called script
 	echo "Usage: $0 option"
-	echo "  - diff     : Show diff between current and saved config"
+	echo "  - diff [quiet|factory]    : Show diff between current and saved config"
 	echo "  - save     : Save current config"
 	echo "  - apply    : Apply current config"
 	echo "  - rollback : Revert to previous config"
@@ -199,7 +200,7 @@ save_cfg () {
 
 	# save ssh keys (conrtibution: to be reviewed)
 	if [ -d /cfg/ssh ]; then
-		cd /etc/ssh
+		cd /etc/ssh || die "can't cd /etc/ssh"
 		for i in "$@" `find ssh_host_* -type f`; do
         	if ! cmp -s /etc/ssh/$i /cfg/ssh/$i; then
 				cp -pfv /etc/ssh/$i /cfg/ssh/$i 2>/dev/null
@@ -224,7 +225,7 @@ save_cfg () {
 apply_cfg () {
 	echo "TO DO: Apply configuration"
 	case "$SECOND_OPTION" in
-        secure)
+	secure)
 		echo "TO DO: Apply config and rollback in $THIRD_OPTION minutes"
 		;;
 	confirm)
@@ -250,51 +251,40 @@ apply_cfg () {
 # Return 0 if no diff found
 # Return 1 if diff found
 diff () {
-	mount_cfg
 	# Don't know how to exchange variable with the subshell
 	# Then using a file in /tmp
-	if [ -f /tmp/DIFF_FOUND ]; then
-		if ! rm /tmp/DIFF_FOUND; then
-			echo "WARNING: Can't delete /tmp/DIFF_FOUND"
-		fi
-	fi
-	if [ ! "$SECOND_OPTION" = "fast" ]; then
+	[ -f /tmp/DIFF_FOUND ] && rm /tmp/DIFF_FOUND
+	[ -z "$SECOND_OPTION" ] && \
 		echo "Looking for differences between running and saved configuration files..."
+	if [ "$SECOND_OPTION" = "factory" ]; then
+		echo "Looking for differences between running and factory default configuration files..."
+		REFERENCE="/conf/base/etc"
+	else
+		REFERENCE="/cfg"
+		mount_cfg
 	fi
 	(
 	cd /etc
 	for i in "$@" `find * -type f`; do
-		if [ -f /cfg/$i ]; then
-			if ! cmp -s /etc/$i /cfg/$i; then
+		if [ -f ${REFERENCE}/$i ]; then
+			if ! cmp -s /etc/$i ${REFERENCE}/$i; then
 				echo "1" > /tmp/DIFF_FOUND
-				if [ ! "$SECOND_OPTION" = "fast" ]; then
-					find $i -print
-				else
-					break
-				fi
+				[ ! "$SECOND_OPTION" = "quiet" ] && find $i -print || break
 			fi
-		else
+		elif [ ! "$SECOND_OPTION" = "conf/base/etc" ]; then
 			if ! cmp -s /conf/base/etc/$i /etc/$i; then
 				echo "1" > /tmp/DIFF_FOUND
-				if [ ! "$SECOND_OPTION" = "fast" ]; then
-					find $i -print
-				else 
-					break
-				fi
+				[ ! "$SECOND_OPTION" = "quiet" ] && find $i -print || break
 			fi
 		fi
 	done
 	)
-	umount_cfg
+	[ ! "$SECOND_OPTION" = "factory" ] && umount_cfg
 	if [ -f /tmp/DIFF_FOUND ]; then
-		if ! rm /tmp/DIFF_FOUND; then
-			echo "WARNING: Can't delete /tmp/DIFF_FOUND"
-		fi
+		rm /tmp/DIFF_FOUND || die "WARNING: Can't delete /tmp/DIFF_FOUND"
 		exit 1
 	else
-		if [ ! "$SECOND_OPTION" = "fast" ]; then
-			echo "None found."
-		fi
+		[ ! "$SECOND_OPTION" = "quiet" ] && echo "None found."
 		exit 0
 	fi
 }
