Change serial and dual port configuration mode with the use of /boot.config only in place of /boot/loader.conf.local, update src and ports, update system and upgrade script

diff --git a/trunk/BSDRP/Files/usr/local/sbin/upgrade b/trunk/BSDRP/Files/usr/local/sbin/upgrade
--- a/trunk/BSDRP/Files/usr/local/sbin/upgrade
+++ b/trunk/BSDRP/Files/usr/local/sbin/upgrade
@@ -127,12 +127,16 @@ write_new_image() {
         	echo "WARNING: Can't backup /boot/loader.conf.local"
     	fi
 	fi
-	# Kept the /boot.config file if exist on source, but not on dest
+
+	# Preserve /boot.config if it's different or not existing
 	# If "system dual-console" was used, this case is triggered
-	if [ -f /boot.config -a ! -f /tmp/sysupgrade/boot.config ]; then
-    	if ! cp /boot.config /tmp/sysupgrade/boot.config; then
-        	echo "WARNING: Can't backup /boot.config"
-    	fi
+	# If user have changed serial speed, this case is triggered
+	if [ -f /boot.config ]; then
+		if ! cmp -s /boot.config /tmp/sysupgrade/boot.config; then
+			if ! cp /boot.config /tmp/sysupgrade/boot.config; then
+       			echo "WARNING: Can't backup /boot.config"
+   			fi
+		fi
 	fi
 	
 	# Adapt fstab of the new system
