update source, add a lock to the IDS-udpate file

diff --git a/EINE/Files/usr/local/sbin/IDS-update b/EINE/Files/usr/local/sbin/IDS-update
--- a/EINE/Files/usr/local/sbin/IDS-update
+++ b/EINE/Files/usr/local/sbin/IDS-update
@@ -4,16 +4,23 @@ set -eu
 CONFIG_FILE="/usr/local/etc/IDS-update.conf"
 SNORT_DIR_RULES="/usr/local/etc/snort/rules/"
 BACKUP_FILE="/tmp/backuped_rules.xz"
+LOCK_FILE="/tmp/IDS-update.lock"
 
 # A usefull function (from: http://code.google.com/p/sh-die/)
-die() { echo -n "EXIT: " >&2; echo "$@" >&2; exit 1; }
+die() {
+    [ -f ${LOCK_FILE} ] && rm ${LOCK_FILE}
+    echo -n "EXIT: " >&2
+    echo "$@" >&2
+    logger "IDS-UPDATE EXIT: $@"
+    exit 1
+}
 
 [ -f ${CONFIG_FILE} ] || logger "IDS-update: No config file found, using default"
 
 backup_rules () {
     echo "backuping existing rules"
     [ -f ${BACKUP_FILE} ] && rm ${BACKUP_FILE}
-    tar -cJf ${BACKUP_FILE} -C ${SNORT_DIR_RULES} .
+    tar -cJf ${BACKUP_FILE} -C ${SNORT_DIR_RULES} . || die "Can't backup existing rules"
 }
 
 checking_rules () {
@@ -21,18 +28,19 @@ checking_rules () {
     if snort -T -c /usr/local/etc/snort/snort.conf; then
         if service snort onestatus; then
             echo "OK, reloading snort"
-            service snort onereload
+            service snort onereload || die "Can't reload snort"
         else
             echo "snort is not running"
         fi
     else
         echo "NOK, restoring previous rules"
+        logger "Bad configuration rules"
         restoring_rules
     fi
 }
 
 restoring_rules () {
-    tar -C ${SNORT_DIR_RULES} -xf ${BACKUP_FILE}
+    tar -C ${SNORT_DIR_RULES} -xf ${BACKUP_FILE} || die "Can't restore previous rules"
 }
 
 cleanup_rules () {
@@ -46,6 +54,11 @@ cleanup_rules () {
 # ET_RULES: List of ET rules to extract
 
 . /usr/local/etc/IDS-update.conf
+
+# If called when already running, exit
+[ -f ${LOCK_FILE} ] && die "IDS update alreay running"
+
+touch ${LOCK_FILE} || die "Can't create lock file"
 
 backup_rules
 
@@ -72,3 +85,5 @@ fi
 checking_rules
 
 cleanup_rules
+
+rm ${LOCK_FILE} || die "Can't delete lock file"
