Add bnxt (Broadcom NetXtreme-C/NetXtreme-E) drivers, new packages: bgpq3 (Generate prefix-list for bird and FRR) and intel-pcm (Tool for displaying PCM counters and energy usage), packages update (bird to 2.0.1, exabgp to 3.4.21), 'show mem' updated for -head (no more vm.stats.vm.v_cache_count, but vm.stats.vm.v_laundry_count), fixing default status for some rc scripts (strongswan, disabletsolro, ), replace ipfw_netflow with the official one, Add pf full cone NAT patch (D11137), Increase VM RAM size on lab-bhyve script (jail/vnet labs needs more than 256MB), sync nanobsd/legacy.sh with -head

diff --git a/BSDRP/Files/usr/local/sbin/config b/BSDRP/Files/usr/local/sbin/config
--- a/BSDRP/Files/usr/local/sbin/config
+++ b/BSDRP/Files/usr/local/sbin/config
@@ -3,7 +3,7 @@
 # Configuration tool for BSD Router Project
 # http://bsdrp.net
 #
-# Copyright (c) 2009-2017, The BSDRP Development Team
+# Copyright (c) 2009-2018, The BSDRP Development Team
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -42,8 +42,11 @@ lock="/var/run/config.bsdrp.lock"
 die() { echo -n "EXIT: " >&2; echo "$@" >&2; exit 1; }
 
 # Because we are using running script, we need to cleanup mess before leaving
+# And forward the original exit code too
 cleanup () {
+	rv=$?
 	[ -d $lock ] && rm -rf $lock
+	exit $rv
 }
 
 # Display help
@@ -179,6 +182,7 @@ archive_cfg () {
 # TODO: Need to backup /boot/loader.conf.local in case of restoring
 #		configuration to other routers
 save_cfg () {
+	setlock
 	mount_cfg || die "ERROR: Can't mount /cfg"
 	archive_cfg || echo "WARNING: Can't archive"
 	echo "Saving configuration..."
@@ -299,6 +303,7 @@ diff () {
 
 # Rollback to previous configuration
 rollback () {
+	setlock
 	echo "Rollback the archived configuration"
 	mount_data || die "ERROR: Can't mount data, then can't retreive archive file"
 	# Check if archive exist
@@ -319,6 +324,7 @@ rollback () {
 # $1 = Source archive filename (.tar.xz)
 # $2 = Destination directory
 restore_cfg ( ) {
+	setlock
 	[ $# -lt 2 ] && die "BUG: restore_cfg(): no enought argument"
 	[ -f $1 ] || die "ERROR: $1 doesn't exist or isn't a file"
 	[ -d $2 ] || die "ERROR: $2 doesn't exist or isn't a directory"
@@ -425,6 +431,7 @@ get () {
 
 # Clear all existing configuration and return to default setting
 factory () {
+	setlock
     echo -n "Clear all saved configuration..."
 	# Autosave will prevent a rollback
 	if service autosave status  > /dev/null 2>&1 ; then
@@ -446,18 +453,21 @@ factory () {
     exit 0
 }
 
+# Set a lock preventing to run this script in parrallel
+setlock () {
+	# We need a method for checking AND creating lock file in same step
+	if ! mkdir $lock 2>/dev/null; then
+		echo "This script is already running (file $lock detected)"
+		usage
+	fi
+}
+
 ###################
 ## Main function ##
 ###################
 
 # Prevent to execute this script twice
 trap cleanup EXIT INT TERM
-
-# We need a method for checking AND creating lock file in same step
-if ! mkdir $lock 2>/dev/null; then
-	echo "This script is already running (file $lock detected)"
-	usage
-fi
 
 # Get options passed by user
 if [ $# -eq 0 ]; then
