Commited net/frr into the FreeBSD port tree, continue to fix the max-features lab

diff --git a/BSDRP/Files/usr/local/sbin/labconfig b/BSDRP/Files/usr/local/sbin/labconfig
--- a/BSDRP/Files/usr/local/sbin/labconfig
+++ b/BSDRP/Files/usr/local/sbin/labconfig
@@ -26,9 +26,9 @@ ifconfig -l | grep -q vtnet && sed -i "" 's/em/vtnet/g' /etc/rc.conf
 echo "net.link.lagg.0.lacp.lacp_strict_mode=0" >> /etc/sysctl.conf
 config save
 hostname R1
+service routing restart || true
 service netif restart
 service sysctl reload
-service routing restart
 service sshd start
 echo "VM1 configured"
 }
@@ -63,6 +63,25 @@ ifconfig -l | grep -q vtnet && sed -i "" 's/em/vtnet/g' /etc/rc.conf
 mount -uw /
 echo "carp_load="YES"" >> /boot/loader.conf.local
 mount -ur /
+
+cat > /usr/local/etc/mpd5/if-up.sh <<EOF
+#!/bin/sh
+set -e
+logger "\$0 called with parameters: \$@"
+if [ "\$2" == "inet6" ]; then
+        if ifconfig \$1 \$2 2001:db8::24:2; then
+        logger "\$0: \$cmd successfull"
+        return 0
+        else
+        logger "\$0: \$cmd failed"
+        return 1
+        fi
+else
+        return 0
+fi
+EOF
+
+chmod +x /usr/local/etc/mpd5/if-up.sh
 
 cat > /usr/local/etc/mpd5/mpd.conf <<EOF
 # Configuring a server PPTP VPN with tunnels to R4
@@ -114,6 +133,8 @@ vpnipv6:
         set bundle enable ipv6cp
         # Remote LAN subnet: Learned by ISIS
         #set iface route 2001:db8:45::/64
+        # Need to statically set inet6 address
+        set iface up-script /usr/local/etc/mpd5/if-up.sh
         # Enable Microsoft Point-to-Point encryption (MPPE)
         set bundle enable compression
         set ccp yes mppc
@@ -185,6 +206,20 @@ router ospf
  area 0.0.0.0 authentication message-digest
 EOF
 
+cat > /usr/local/etc/frr/ospf6d.conf <<EOF
+interface ng0
+ ipv6 ospf6 passive
+interface ng1
+ ipv6 ospf6 network point-to-point
+router ospf6
+ router-id 0.0.0.4
+ redistribute isis
+ interface ng1 area 0.0.0.0
+ interface em0 area 0.0.0.0
+ interface vtnet0 area 0.0.0.0
+EOF
+
+
 config save
 hostname R2
 kldload carp
@@ -252,25 +287,6 @@ add 10.0.23.3 10.0.23.2 tcp 0x1001 -A tcp-md5 "abigpassword" ;
 add -6 2001:db8:23::2 2001:db8:23::3 tcp 0x1002 -A tcp-md5 "abigpassword" ;
 add -6 2001:db8:23::3 2001:db8:23::2 tcp 0x1003 -A tcp-md5 "abigpassword" ;
 EOF
-
-cat > /usr/local/etc/frr/bgpd.conf <<EOF
-router bgp 100
- bgp router-id 0.0.0.3
- network 10.0.3.0/24
- network 10.0.34.0/24
- neighbor 10.0.23.2 remote-as 100
- neighbor 10.0.23.2 soft-reconfiguration inbound
- neighbor 2001:db8:23::2 remote-as 100
- no neighbor 2001:db8:23::2 activate
-!
- address-family ipv6
- network 2001:db8:3::/64
- network 2001:db8:34::/64
- neighbor 2001:db8:23::2 activate
- neighbor 2001:db8:23::2 soft-reconfiguration inbound
- exit-address-family
-EOF
-
 
 cat > /usr/local/etc/bird.conf <<EOF
 # Configure logging
@@ -341,7 +357,7 @@ protocol rip R4 {
 
 protocol bgp R2 {
         local as 100;
-        neighbor 2001:db8:6::2 as 100;
+        neighbor 2001:db8:23::2 as 100;
         import all;
         export all;
 }
@@ -419,9 +435,14 @@ router ospf
 EOF
 
 cat > /usr/local/etc/frr/ospf6d.conf <<EOF
+interface ng0
+ ipv6 ospf6 passive
+interface ng1
+ ipv6 ospf6 network point-to-point
 router ospf6
  router-id 0.0.0.4
- interface ng0 area 0.0.0.0
+ redistribute isis
+ interface ng1 area 0.0.0.0
  interface lo1 area 0.0.0.0
 EOF
 
@@ -439,6 +460,25 @@ router isis BSDRP
  redistribute ipv4 ospf level-1
  redistribute ipv6 ospf6 level-1
 EOF
+
+cat > /usr/local/etc/mpd5/if-up.sh <<EOF
+#!/bin/sh
+set -e
+logger "\$0 called with parameters: \$@"
+if [ "\$2" == "inet6" ]; then
+        if ifconfig \$1 \$2 2001:db8::24:4; then
+        logger "\$0: \$cmd successfull"
+        return 0
+        else
+        logger "\$0: \$cmd failed"
+        return 1
+        fi
+else
+        return 0
+fi
+EOF
+
+chmod +x /usr/local/etc/mpd5/if-up.sh
 
 cat > /usr/local/etc/mpd5/mpd.conf <<EOF
 default:
@@ -488,6 +528,8 @@ vpnipv6:
         set bundle enable ipv6cp
         # Remote LAN subnet: Learned by ISIS
         #set iface route 2001:db8:12::/64
+        # Need to statically configure inet6 adress
+        set iface up-script /usr/local/etc/mpd5/if-up.sh
         # Create a static pptp link called lvpnipv6
         create link static lvpnipv6 pptp
         # Attach this link to vpnipv6
@@ -660,8 +702,8 @@ sysrc ipv6_gateway_enable=NO
 ifconfig -l | grep -q vtnet && sed -i "" 's/em/vtnet/g' /etc/rc.conf
 config save
 hostname R6
+service routing restart || true
 service netif restart
-service routing restart
 service bsnmpd start
 echo "VM6 configured"
 }
