Add mstlint to the -lite version, update port tree, fix bisec gen tool, update exabgp and FRR

diff --git a/BSDRP/Files/usr/local/sbin/post-upgrade b/BSDRP/Files/usr/local/sbin/post-upgrade
--- a/BSDRP/Files/usr/local/sbin/post-upgrade
+++ b/BSDRP/Files/usr/local/sbin/post-upgrade
@@ -3,7 +3,7 @@
 # Post-upgrade fixup tool for BSD Router Project
 # https://bsdrp.net
 #
-# Copyright (c) 2009-2017, The BSDRP Development Team
+# Copyright (c) 2009-2020, The BSDRP Development Team
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -89,6 +89,24 @@ if grep -q '^1.7' /etc/version; then
 			chown -R 168:168 /cfg/local/frr/
 		fi
 		umount /cfg
+	fi
+fi
+
+# Check if /etc/fstab contains special directories (
+CFG_UMOUNT=true
+if ! grep -q fdesc /etc/fstab; then
+	if mount | ! grep -q "/cfg"; then
+		mount /cfg || die "cannot mount /cfg"
+	else
+		CFG_UMOUNT=false
+	fi
+	(
+	echo "fdesc   /dev/fd         fdescfs         rw      0       0"
+	echo "proc    /proc           procfs          rw      0       0"
+	) >> /cfg/fstab
+	cp /cfg/fstab /etc/ || die "Cannot copy patched /cfg/fstab into /etc"
+	if (${CFG_UMOUNT}); then
+		umount /cfg || true
 	fi
 fi
 
