Fix system expand-data-slice (and style), update port-tree

diff --git a/BSDRP/Files/usr/local/sbin/system b/BSDRP/Files/usr/local/sbin/system
--- a/BSDRP/Files/usr/local/sbin/system
+++ b/BSDRP/Files/usr/local/sbin/system
@@ -85,8 +85,8 @@ dual_console () {
 	SERIAL_SPEED=`grep ttyu0 /etc/ttys | cut -d'.' -f 2 | cut -d '"' -f 1`
 	# Check that we get something regarding serial speed
 	[ -z "${SERIAL_SPEED}" ] && die "Can't determine serial speed from ttyu0 on /etc/ttys"
-	[ ${SERIAL_SPEED} -lt 9600 ] && die "Incorrect serial speed value: ${SERIAL_SPEED}"
-	[ ${SERIAL_SPEED} -gt 115200 ] && die "Incorrect serial speed value: ${SERIAL_SPEED}"
+	[ ${SERIAL_SPEED} -lt 9600 ] && die "Incorrect serial speed value: ${SERIAL_SPEED}"
+	[ ${SERIAL_SPEED} -gt 115200 ] && die "Incorrect serial speed value: ${SERIAL_SPEED}"
 	echo "-S${SERIAL_SPEED} -Dh" > /boot.config
 	mount -ur / || die "Error for remounting / in RO mode"
 }
@@ -138,49 +138,56 @@ expand_data_slice () {
 	. /etc/nanobsd.conf
 
 	if [ `uname -m` = "sparc64" ]; then
-		boot_dev=/dev/`glabel status | grep ${NANO_DRIVE}s1a | awk '{ print $3; }' | sed 's/.$//'`
-		echo "Not supported: sparc64 for this function"
-		exit 0
+		boot_dev=/dev/`glabel status | grep ${NANO_DRIVE}s1a \
+			 | awk '{ print $3; }' | sed 's/.$//'`
+		die "Not supported: sparc64 for this function"
 	else
-		boot_dev=/dev/`glabel status | grep ${NANO_DRIVE}s1a | awk '{ print $3; }' | cut -d s -f 1`
+		boot_dev=/dev/`glabel status | grep ${NANO_DRIVE}s1a \
+			 | awk '{ print $3; }' | cut -d s -f 1`
 	fi
 	label=`cut -d '/' -f 2 /etc/nanobsd.conf`
 
 	if mount | grep -q "/data"; then
 		die "/data is mounted, you need to unmount it"
-    fi
+	fi
 
 	#free space
-	FREE_SPACE=`gpart show ${boot_dev} | grep "\- free \-" | grep -v k | cut -d '-' -f 3`
-	[ -z ${FREE_SPACE} ] && die "There is no space left on disk"
+	FREE_SPACE=`gpart show ${boot_dev} | grep "\- free \-" | grep -v k \
+			   | cut -d '-' -f 3 | tr -s ' '`
+	[ -z "${FREE_SPACE}" ] && die "There is no space left on disk"
 	echo "There is ${FREE_SPACE} available on your disk that can be use for /data"
 	echo -n "Are you sure to repartition your disk ? (y/n)"
-    while [ "$USER_CONFIRM" != "y" -a "$USER_CONFIRM" != "n" ]; do
-        read USER_CONFIRM <&1
-    done
-    [ "$USER_CONFIRM" = "n" ] && die "User cancel"
+    	while [ "$USER_CONFIRM" != "y" -a "$USER_CONFIRM" != "n" ]; do
+        	read USER_CONFIRM <&1
+    	done
+	[ "$USER_CONFIRM" = "n" ] && die "User cancel"
 
 	# Using "gpart resize" + growfs  is too slow and create a bug with 
 	# the geom label (pr=kern/165962)
 	#
 
 	# Backup the s4 (data) partion
-	dump -0auf/tmp/s4.dump ${NANO_DRIVE}s4 || die "ERROR: dumping ${NANO_DRIVE}s4 to /tmp failed"
+	dump -0auf/tmp/s4.dump /dev/${NANO_DRIVE}s4 \
+	|| die "ERROR: dumping ${NANO_DRIVE}s4 to /tmp failed"
 
 	# Deleting partition s4
 	# Need to check the partition delete on sparc64
-	gpart delete -i 4 ${boot_dev} || die "Unable to gpart delete -i 4 ${boot_dev}"
+	gpart delete -i 4 ${boot_dev} \
+	|| die "Unable to gpart delete -i 4 ${boot_dev}"
 
 	# Recreating s4 using full disk space
-	gpart add -t freebsd-ufs ${boot_dev} || die "Unable gpart add -t freebsd ${boot_dev}"
+	gpart add -t freebsd ${boot_dev} \
+	|| die "Unable gpart add -t freebsd ${boot_dev}"
 
 	# Formatting the new partition (SUJ)
 	LABEL=`cut -f 2 -d "/" /etc/nanobsd.conf`
-	newfs -UjL ${LABEL}s4 ${boot_dev}s4 || die "Unable to newfs -UjtL ${LABEL}s4 ${boot_dev}s4"
+	newfs -UjL ${LABEL}s4 ${boot_dev}s4 \
+	|| die "Unable to newfs -UjtL ${LABEL}s4 ${boot_dev}s4"
 
 	# Restoring the dump
 	[ -d /tmp/slice ] || mkdir -p /tmp/slice
-	mount ${NANO_DRIVE}s4 /tmp/slice || die "Unable to mount ${NANO_DRIVE}s4 /tmp/slice"
+	mount /dev/${NANO_DRIVE}s4 /tmp/slice \
+	|| die "Unable to mount /dev/${NANO_DRIVE}s4 /tmp/slice"
 	cd /tmp/slice
 	restore rf /tmp/s4.dump || die "Unable to restore rf /tmp/s4.dump"
 	[ -f /tmp/slice/restoresymtable ] && rm -rf /tmp/slice/restoresymtable
@@ -204,24 +211,27 @@ rollback () {
 	NANO_GLABEL_SYS=`cut -d '/' -f 2 /etc/nanobsd.conf`
 	# Get the NANO_GLABEL_SYS_FULL variable
 	# (kept the last number: 1 or 2)
-	NANO_GLABEL_SYS_FULL=`mount | grep " / " | cut -d'/' -f4 | cut -d' ' -f1`
+	NANO_GLABEL_SYS_FULL=`mount | grep " / " | cut -d'/' -f4 \
+	| cut -d' ' -f1`
 
 	# Get the disk name using its label
-	NANO_DRIVE=`glabel status | grep ufs/${NANO_GLABEL_SYS_FULL} | awk '{print $3}' | cut -d's' -f1`
+	NANO_DRIVE=`glabel status | grep ufs/${NANO_GLABEL_SYS_FULL} \
+	| awk '{print $3}' | cut -d's' -f1`
 
 	# Get the full disk name
-	NANO_FULLDRIVE=`glabel status | grep ufs/${NANO_GLABEL_SYS_FULL} | awk '{print $3}'`
+	NANO_FULLDRIVE=`glabel status | grep ufs/${NANO_GLABEL_SYS_FULL} \
+	| awk '{print $3}'`
 
 	# Check and set final variable
 	DST_SLICE=0
 
 	if [ `echo $NANO_FULLDRIVE | /usr/bin/grep "s1"` ]; then 
-    	DST_SLICE=2
-    	SRC_SLICE=1
+    		DST_SLICE=2
+    		SRC_SLICE=1
 	fi
 	if [ `echo $NANO_FULLDRIVE | /usr/bin/grep "s2"` ]; then                
-    	DST_SLICE=1
-    	SRC_SLICE=2
+    		DST_SLICE=1
+    		SRC_SLICE=2
 	fi
 
 	[ $DST_SLICE = 0 ] && die "Can't detect active slice"
@@ -236,37 +246,35 @@ rollback () {
 
 	echo -n "Warning: Are you sure to revert to the previous release ? (y/n)"
 	while [ "$USER_CONFIRM" != "y" -a "$USER_CONFIRM" != "n" ]; do
-       	read USER_CONFIRM <&1
+       		read USER_CONFIRM <&1
 	done
-	if [ "$USER_CONFIRM" = "n" ]; then
-		exit 0	
-	fi
+	[ "$USER_CONFIRM" = "n" ] && exit 0
 
 	# Need to compare some files between the old and new partition
 	[ -d /tmp/sysupgrade ] || mkdir /tmp/sysupgrade
 
 	#   Adapt fstab of the old system
-    sed -i "" "s/${NANO_GLABEL_SYS}s${SRC_SLICE}a/${NANO_GLABEL_SYS}s${DST_SLICE}a/g" /etc/fstab
+	sed -i "" "s/${NANO_GLABEL_SYS}s${SRC_SLICE}a/${NANO_GLABEL_SYS}s${DST_SLICE}a/g" /etc/fstab
 
 	# Save the config file that include the fstab
 	mount /cfg || die "ERROR: Cant't mount /cfg"
 	if ! cp /etc/fstab /cfg; then
-    	umount /cfg
+    		umount /cfg
 		die "ERROR: Can't save fstab"
 	fi
 	umount /cfg || die "ERROR: Can't umount /cfg"
 	case `uname -m` in
-		i386|amd64)
-			boot0cfg -s ${DST_SLICE} -t 18 -v ${NANO_DRIVE} ||
-				die "ERROR: Can't update FreeBSD bootloader"
+	i386|amd64)
+		boot0cfg -s ${DST_SLICE} -t 18 -v ${NANO_DRIVE} ||
+		   die "ERROR: Can't update FreeBSD bootloader"
            
-			gpart set -a active -i ${DST_SLICE} ${NANO_DRIVE} ||
-				die "ERROR: Can't update active partition"
+		gpart set -a active -i ${DST_SLICE} ${NANO_DRIVE} ||
+		   die "ERROR: Can't update active partition"
                 ;;
         arm)
                 echo "arm upgrade script not tested!"   
                 gpart set -a active -i ${DST_SLICE} ${NANO_DRIVE} ||
-                    die "ERROR: Can't update active partition"
+                   die "ERROR: Can't update active partition"
                 ;;
         sparc64)
                 echo "You need to configure OBP for booting on"
@@ -336,11 +344,11 @@ check_cfg () {
 	echo "Checking if configuration is saved..."
 	# Don't know why I can't test the exist value of config diff quit in my if
 	set +e
-    config diff fast
-    if [ $? -eq 1 ]; then
-        ask_save
-    fi
-    set -e
+	config diff fast
+	if [ $? -eq 1 ]; then
+        	ask_save
+	fi
+	set -e
 }
 
 # Reboot
@@ -362,30 +370,22 @@ sys_halt () {
 # Check if system is under a VM
 check_vm () {
 	# Look for VM environnement
-	if sysctl -n kern.vm_guest | grep -q "none"; then
-		VM_FOUND=false
-	else
-       	VM_FOUND=true
-   	fi
-    if (${VM_FOUND}); then
-		if [ "${SECOND_OPTION}" != "quiet" ]; then
-        	echo "VM environnement detected"
-		fi
-    fi
+	sysctl -n kern.vm_guest | grep -q "none" &&  VM_FOUND=false \
+		|| VM_FOUND=true
+	if (${VM_FOUND}); then
+		[ "${SECOND_OPTION}" != "quiet" ] \
+		    && echo "VM environnement detected"
+	fi
 	
 	KERN_HZ=`sysctl -n kern.hz`
-	if [ ${KERN_HZ} -gt 100 ]; then
-		NOT_TUNED=true
-	else
-		NOT_TUNED=false
-	fi
+	[ ${KERN_HZ} -gt 100 ] && NOT_TUNED=true || NOT_TUNED=false
 
 	# Stupid if, but don't know how to use an "add" condition in the if
-    if ( ${VM_FOUND} ) && ( ${NOT_TUNED} ); then
-       	echo "WARNING: Current (Default) kern.hz value too high for a VM use!"
-       	echo 'Use "system virtualized" for lower it'
+	if ( ${VM_FOUND} ) && ( ${NOT_TUNED} ); then
+       		echo "WARNING: Current (Default) kern.hz value too high for a VM use!"
+       		echo 'Use "system virtualized" for lower it'
 	fi
-    exit 0
+	exit 0
 }
 
 # Tune for VM usage
