update source tree: pf speed improvement, Fix /etc/rc.conf.misc conversion to /etc/rc.conf.d/

diff --git a/BSDRP/Files/usr/local/sbin/system b/BSDRP/Files/usr/local/sbin/system
--- a/BSDRP/Files/usr/local/sbin/system
+++ b/BSDRP/Files/usr/local/sbin/system
@@ -3,7 +3,7 @@
 # System tool for BSD Router Project
 # https://bsdrp.net
 #
-# Copyright (c) 2009-2019, The BSDRP Development Team
+# Copyright (c) 2009-2021, The BSDRP Development Team
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -327,7 +327,9 @@ rollback () {
 # Check if cfg was modified
 check_cfg () {
 	# Testing /etc/rc.conf
-	sh /etc/rc.conf || die "There is an error in /etc/rc.conf file"
+	if [ -f /etc/rc.conf ]; then
+		sh /etc/rc.conf || die "There is an error in /etc/rc.conf file"
+	fi
 	echo "Checking if configuration is saved..."
 	config diff quiet || ask_save
 }
